shared:
  num_classes: &num_classes 4
  num_epochs: &num_epochs 20
  validation_period: &val_period 5
  train_file: &train train_walrus/test_5.json
  train_imgs_dir: &train_imgs_dir dataset/images
  valid_file: &valid train_walrus/test_5.json
  valid_imgs_dir: &valid_imgs_dir dataset/images
  images_height: &img_h 416
  images_width: &img_w 416

runner:
  _target_: YOLOXDetectionRunner

args: # Различные аргументы для Catalyst
  expdir: src/detection # Путь до нашего эксперимента, с файлом `__init__`, в котором импортируется Runner, и, опционально, регистрируются все дополнительные сущности: model, callback, criterion, etc
  logdir: logs # Путь в который будут сохранятся логи
  verbose: True # Нужно ли выводить на консоль информацию об обучении
  seed: 42 # сид обучения для PyTorch, Numpy, Python и Tensorflow
  deterministic: True # Нужно ли использовать deterministic CuDNN
  benchmark: True # Нужно ли использовать CuDNN benchmark
engine:
  _target_: DeviceEngine
  device: cuda
model:
  _target_: yolo_x_tiny
  num_classes: *num_classes

loggers:
  console:
    _target_: ConsoleLogger
  # mlflow:
  #   _target_: MLflowLogger
  #   experiment: 'detection'

stages:
  initial_training:
    num_epochs: *num_epochs

    loaders: &loaders
      batch_size: 4
      num_workers: 4
      
      datasets:
        train:
          _target_: YOLOXDataset
          coco_json_path: *train
          images_dir: *train_imgs_dir
          transforms:
            _target_: albumentations.Compose
            transforms:
              - _target_: albu.Resize
                height: *img_h
                width: *img_w
              - _target_: albu.Normalize
              - _target_: albu.ToTensorV2
            bbox_params:
              _target_: albu.BboxParams
              format: albumentations

        valid:
          _target_: YOLOXDataset
          coco_json_path: *valid
          images_dir: *valid_imgs_dir
          transforms:
            _target_: albumentations.Compose
            transforms:
              - _target_: albu.Resize
                height: *img_h
                width: *img_w
              - _target_: albu.Normalize
              - _target_: albu.ToTensorV2
            bbox_params:
              _target_: albu.BboxParams
              format: albumentations

    optimizer:
      _target_: torch.optim.AdamW
      lr: 0.001

    callbacks: &callbacks
      periodic_validation:
        _target_: catalyst.callbacks.PeriodicLoaderCallback
        valid_loader_key: valid
        valid_metric_key: mAP
        minimize: False
        valid: *val_period

      mAP:
        _target_: DetectionMeanAveragePrecision
        num_classes: *num_classes
        output_type: yolo-x
        iou_threshold: 0.5
        confidence_threshold: 0.25

      optimizer:
        _target_: catalyst.callbacks.OptimizerCallback
        metric_key: loss