convert: False
# Параметры для resize
width: 224
height: 224
channels: 3

dataset_path: "./test_dataset" # Путь до папки датасета содержащей папки: train, val, base
num_workers: 0
batch_size: 32
pin_memory: True
output_dataset_path: "./lmdb_test_dataset" # Путь до папки в котором сохранится lmdb датасет
